"""empty message

Revision ID: 7ac1cba31fbe
Revises: 
Create Date: 2021-06-23 14:10:59.219902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac1cba31fbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movie_release_date', sa.Date(), nullable=True))
    op.add_column('movie', sa.Column('movie_title', sa.String(), nullable=True))
    op.drop_column('movie', 'movies_title')
    op.drop_column('movie', 'movies_release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('movies_release_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('movie', sa.Column('movies_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('movie', 'movie_title')
    op.drop_column('movie', 'movie_release_date')
    # ### end Alembic commands ###
